name: Build, Push and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  # ========================
  # STAGE 1 — BUILD
  # ========================
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t gowrishankar0o/simple-html-app:latest .


  # ========================
  # STAGE 2 — PUSH
  # ========================
  push:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image (Again)
      run: |
        docker build -t gowrishankar0o/simple-html-app:latest .

    - name: Push Docker Image
      run: |
        docker push gowrishankar0o/simple-html-app:latest


  # ========================
  # STAGE 3 — DEPLOY
  # ========================
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: |
          ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Stopping old container..."
          sudo docker stop myapp || true

          echo "Removing old container..."
          sudo docker rm myapp || true

          echo "Pulling latest image..."
          sudo docker pull gowrishankar0o/simple-html-app:latest

          echo "Starting new container..."
          sudo docker run -d \
            -p 80:80 \
            --restart always \
            --name myapp \
            gowrishankar0o/simple-html-app:latest

          echo "Deployment successful!"
